// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/groq.json" with { type: "json" };
import { flattenChatModelCatalog, flattenClassifierModelCatalog, flattenImageModelCatalog, type ChatModelCatalog, type ClassifierModelCatalog, type ImageModelCatalog } from "../model-catalog.ts";

export const GROQ_MODELS: ChatModelCatalog<typeof values, "groq"> =
	flattenChatModelCatalog("groq", values);

export const GROQ_IMAGE_MODELS: ImageModelCatalog<typeof values, "groq"> =
	flattenImageModelCatalog("groq", values);

export const GROQ_CLASSIFIER_MODELS: ClassifierModelCatalog<typeof values, "groq"> =
	flattenClassifierModelCatalog("groq", values);
