// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/openai.json" with { type: "json" };
import { flattenChatModelCatalog, flattenClassifierModelCatalog, flattenImageModelCatalog, type ChatModelCatalog, type ClassifierModelCatalog, type ImageModelCatalog } from "../model-catalog.ts";

export const OPENAI_MODELS: ChatModelCatalog<typeof values, "openai"> =
	flattenChatModelCatalog("openai", values);

export const OPENAI_IMAGE_MODELS: ImageModelCatalog<typeof values, "openai"> =
	flattenImageModelCatalog("openai", values);

export const OPENAI_CLASSIFIER_MODELS: ClassifierModelCatalog<typeof values, "openai"> =
	flattenClassifierModelCatalog("openai", values);
